#[derive(Debug, Clone, PartialEq)]
pub enum OpCode {
    Constant(usize),
    Add,
    Subtract,
    Multiply,
    Divide,
    Equal,
    Greater,
    Less,
    Jump(usize),
    JumpIfFalse(usize),
    StringLength,
    StringContainsChars,
    StringSplit,
    ArrayContains,
    ReadFile,
    ExternCall { name_idx: usize, arg_count: usize },
    SetGlobal(usize),
    GetGlobal(usize),
    SetLocal(usize),
    GetLocal(usize),
    Call(usize, usize),
    AllocateDict,
    GetProperty,
    SetProperty,
    Pop,
    Print,
    Return,
}
