[package]
name = "knoten_core"
version = "1.1.0"
edition = "2024"



[[bin]]
name = "run_knc"
path = "src/bin/run_knc.rs"

[[bin]]
name = "bench_knc"
path = "src/bin/bench_knc.rs"

[[bin]]
name = "knoten_build"
path = "src/bin/knoten_build.rs"

[[bin]]
name = "rust_ingest"
path = "src/bin/rust_ingest.rs"

[[bin]]
name = "knoten_upgrade"
path = "src/bin/knoten_upgrade.rs"

[[bin]]
name = "knoten_lsp"
path = "src/bin/knoten_lsp.rs"

[dependencies]
dunce = "1.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
cpal = "0.15.3"
pollster = "0.4.0"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
wgpu = "23.0"
winit = "0.30"
image = "0.25.1"
hound = "3.5.1"
serde_json = "1.0.149"
egui = "0.30"
egui-wgpu = "0.30"
egui-winit = "0.30"
rodio = "0.19.0"
noise = "0.9.0"
glam = { version = "0.32.0", features = ["bytemuck"] }
ureq = "2.9.1"
tower-lsp = { version = "0.20.0", features = ["runtime-tokio"] }
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
dashmap = "6.1.0"
regex = "1.10"
[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
